---
abstract: 'Test::Run plugin to collect statistics and'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Test::More: 0
  Test::Trap: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Run-Plugin-CollectStats
provides:
  Test::Run::Plugin::CollectStats:
    file: lib/Test/Run/Plugin/CollectStats.pm
    version: 0.0103
  Test::Run::Plugin::CollectStats::TestFileData:
    file: lib/Test/Run/Plugin/CollectStats/TestFileData.pm
requires:
  MRO::Compat: 0
  Moose: 0
  Storable: 0
  Test::Run::Base::Struct: 0
  Test::Run::Core: 0.0106
  perl: 5.008
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: 0.0103
